In [1]:
import sklearn

In [2]:
sklearn.__version__

'0.24.2'

In [3]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [4]:
import pandas as pd

In [5]:
iris = load_iris(as_frame=True)

In [6]:
type(iris)

sklearn.utils.Bunch

In [7]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [8]:
iris['data']

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [9]:
iris.data

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [10]:
iris.target

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int32

In [11]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [12]:
iris

{'data':      sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
 0                  5.1               3.5                1.4               0.2
 1                  4.9               3.0                1.4               0.2
 2                  4.7               3.2                1.3               0.2
 3                  4.6               3.1                1.5               0.2
 4                  5.0               3.6                1.4               0.2
 ..                 ...               ...                ...               ...
 145                6.7               3.0                5.2               2.3
 146                6.3               2.5                5.0               1.9
 147                6.5               3.0                5.2               2.0
 148                6.2               3.4                5.4               2.3
 149                5.9               3.0                5.1               1.8
 
 [150 rows x 4 columns],
 'target': 0     

In [13]:
iris_df = iris['data']

In [14]:
iris_df['target'] = iris['target']

In [15]:
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [16]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [163]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size= 0.2, random_state=101)

# test_size : 20% 쓰겠다 (데이터를 분리하였음) / random_state = 시드값? 제각각 나와.. 0으로 하면 똑같은 패턴으로 나옴
# stratify = 비율을 동일하게 잡아서 뽑아줌, 타겟값을 넣어주면 됨.. 

In [164]:
X_train, X_test, y_train, y_test

(array([[6.5, 3. , 5.8, 2.2],
        [5.5, 2.5, 4. , 1.3],
        [6.5, 3. , 5.5, 1.8],
        [5.8, 2.7, 3.9, 1.2],
        [6.8, 3. , 5.5, 2.1],
        [5.7, 2.8, 4.5, 1.3],
        [6.7, 3.1, 4.7, 1.5],
        [5.9, 3. , 4.2, 1.5],
        [5.6, 2.7, 4.2, 1.3],
        [7.7, 3. , 6.1, 2.3],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [6.7, 3. , 5. , 1.7],
        [5.6, 3. , 4.5, 1.5],
        [4.3, 3. , 1.1, 0.1],
        [7.1, 3. , 5.9, 2.1],
        [5.8, 2.7, 4.1, 1. ],
        [4.9, 3.1, 1.5, 0.2],
        [5.1, 2.5, 3. , 1.1],
        [5.6, 2.5, 3.9, 1.1],
        [5.1, 3.3, 1.7, 0.5],
        [5.8, 2.7, 5.1, 1.9],
        [5. , 3.6, 1.4, 0.2],
        [4.9, 2.4, 3.3, 1. ],
        [6.7, 2.5, 5.8, 1.8],
        [5.8, 2.6, 4. , 1.2],
        [4.9, 3.6, 1.4, 0.1],
        [5.1, 3.4, 1.5, 0.2],
        [6.1, 3. , 4.6, 1.4],
        [4.6, 3.4, 1.4, 0.3],
        [6.4, 3.2, 4.5, 1.5],
        [7.7, 2.6, 6.9, 2.3],
        [6

In [165]:
type(X_train)

numpy.ndarray

##### 모델을 만들엇대..

In [109]:
dt_clf = DecisionTreeClassifier()

### 학습을 해보래... (변수.fit)

In [110]:
dt_clf.fit(X_train, y_train) # y_train : 답

DecisionTreeClassifier()

### 검증을 하래... (변수.predict)

In [114]:
pred = dt_clf.predict(X_test) # 예측값 저장

In [115]:
pred

array([0, 0, 0, 2, 1, 2, 1, 1, 2, 0, 2, 0, 0, 2, 2, 1, 1, 1, 0, 2, 1, 0,
       1, 1, 1, 1, 1, 2, 0, 0])

In [116]:
y_test

33     0
16     0
43     0
129    2
50     1
123    2
68     1
53     1
146    2
1      0
147    2
32     0
31     0
122    2
127    2
74     1
88     1
96     1
42     0
134    2
80     1
48     0
90     1
65     1
97     1
64     1
93     1
114    2
25     0
41     0
Name: target, dtype: int32

##### 답을 눈으로 확인하기 힘드니까 밑에 잇는걸 쓴다

In [117]:
from sklearn.metrics import accuracy_score # 평가관련하여 모든게 다 들어가있다 / 분류에서 맞냐 틀리냐..

In [118]:
accuracy_score(y_test, pred) #첫번째는 정답이 들어있는 변수, 두번째는 컴이 내놓은 답이 들어있는 변수

1.0

#### fit_transform().. 도 잇다고 한다

In [72]:
# feature : 독립변수 (x값)

#### 함수설명....

In [130]:
def test1(a,b):
    '''
    이 함수는 결과값이 3개로 나갑니다.
    '''
    return a+b, a-b, a*b

In [ ]:
test1()

In [121]:
result = test1(1,2)

In [123]:
result

(3, -1, 2)

In [124]:
r1, r2, r3 = test1(3,4)

In [126]:
r1

7

In [127]:
r2

-1

In [128]:
r3

12

### 과적합 참조
![과적합](과적합.png)

```
print('hello')
```

In [196]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

In [197]:
iris = load_iris()
dt_clf = DecisionTreeClassifier(random_state = 156)

In [198]:
kfold = KFold(n_splits = 5, shuffle = True)

In [199]:
cv_accuracy = []

In [200]:
iris.data.shape # shape : 몇행의 몇열인가를 알려줌

(150, 4)

In [201]:
n_iter = 0  #반복체크하는 용도
for train_index, test_index in kfold.split(iris.data): # split : 얘가 인덱스 값을 뽑아줌
    # print(train_index)
    # print("-"*50)
    # print(test_index)
    # print()
    X_train, X_test = iris.data[train_index], iris.data[test_index]
    # print(X_train, X_test)
    y_train, y_test = iris.target[train_index], iris.target[test_index]
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    accuracy = accuracy_score(y_test, pred)
    cv_accuracy.append(accuracy)
    n_iter += 1 # 1씩 증가
    print(f'{n_iter}번째 교차검증')
    print(f'학습데이터 건수: {X_train.shape[0]}, 검증데이터 건수: {X_test.shape[0]}')
    print(f'정확도: {accuracy}')
print(np.mean(cv_accuracy))

1번째 교차검증
학습데이터 건수: 120, 검증데이터 건수: 30
정확도: 0.9666666666666667
2번째 교차검증
학습데이터 건수: 120, 검증데이터 건수: 30
정확도: 0.9666666666666667
3번째 교차검증
학습데이터 건수: 120, 검증데이터 건수: 30
정확도: 0.9333333333333333
4번째 교차검증
학습데이터 건수: 120, 검증데이터 건수: 30
정확도: 1.0
5번째 교차검증
학습데이터 건수: 120, 검증데이터 건수: 30
정확도: 0.8333333333333334
0.9400000000000001


In [202]:
kfold = KFold(n_splits = 5, shuffle = True)
n_iter = 0  #반복체크하는 용도

for train_index, test_index in kfold.split(iris.data): # split : 얘가 인덱스 값을 뽑아줌
    X_train, X_test = iris.data[train_index], iris.data[test_index]
    y_train, y_test = iris.target[train_index], iris.target[test_index]
    
    print('학습용데이터 분포:\n',pd.Series(y_train).value_counts()) # numpy의 ndarray는 value_count가 없어.. 그래서 series나 데이터프레임으로 만듦
    print('검증용데이터 분포:\n',pd.Series(y_test).value_counts())

학습용데이터 분포:
 1    41
0    40
2    39
dtype: int64
검증용데이터 분포:
 2    11
0    10
1     9
dtype: int64
학습용데이터 분포:
 1    43
0    42
2    35
dtype: int64
검증용데이터 분포:
 2    15
0     8
1     7
dtype: int64
학습용데이터 분포:
 2    43
0    41
1    36
dtype: int64
검증용데이터 분포:
 1    14
0     9
2     7
dtype: int64
학습용데이터 분포:
 0    43
2    40
1    37
dtype: int64
검증용데이터 분포:
 1    13
2    10
0     7
dtype: int64
학습용데이터 분포:
 1    43
2    43
0    34
dtype: int64
검증용데이터 분포:
 0    16
1     7
2     7
dtype: int64


In [203]:
from sklearn.model_selection import StratifiedKFold

In [204]:
skfold = StratifiedKFold(n_splits = 5, shuffle = True)
n_iter = 0  #반복체크하는 용도

for train_index, test_index in skfold.split(iris.data, iris.target): # split : 얘가 인덱스 값을 뽑아줌
    X_train, X_test = iris.data[train_index], iris.data[test_index]
    y_train, y_test = iris.target[train_index], iris.target[test_index]
    
    print('학습용데이터 분포:\n',pd.Series(y_train).value_counts()) # numpy의 ndarray는 value_count가 없어.. 그래서 series나 데이터프레임으로 만듦
    print('검증용데이터 분포:\n',pd.Series(y_test).value_counts())

학습용데이터 분포:
 0    40
1    40
2    40
dtype: int64
검증용데이터 분포:
 0    10
1    10
2    10
dtype: int64
학습용데이터 분포:
 0    40
1    40
2    40
dtype: int64
검증용데이터 분포:
 0    10
1    10
2    10
dtype: int64
학습용데이터 분포:
 0    40
1    40
2    40
dtype: int64
검증용데이터 분포:
 0    10
1    10
2    10
dtype: int64
학습용데이터 분포:
 0    40
1    40
2    40
dtype: int64
검증용데이터 분포:
 0    10
1    10
2    10
dtype: int64
학습용데이터 분포:
 0    40
1    40
2    40
dtype: int64
검증용데이터 분포:
 0    10
1    10
2    10
dtype: int64


In [213]:
skfold = StratifiedKFold(n_splits = 5, shuffle = True)
n_iter = 0  #반복체크하는 용도
cv_accuracy = []
for train_index, test_index in skfold.split(iris.data, iris.target): 

    X_train, X_test = iris.data[train_index], iris.data[test_index]
    y_train, y_test = iris.target[train_index], iris.target[test_index]
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    accuracy = accuracy_score(y_test, pred)
    cv_accuracy.append(accuracy)
    n_iter += 1
    print(f'{n_iter}번째 교차검증')
    print(f'학습데이터 건수: {X_train.shape[0]}, 검증데이터 건수: {X_test.shape[0]}')
    print(f'정확도: {accuracy}')
print(np.mean(cv_accuracy))

1번째 교차검증
학습데이터 건수: 120, 검증데이터 건수: 30
정확도: 0.9666666666666667
2번째 교차검증
학습데이터 건수: 120, 검증데이터 건수: 30
정확도: 0.8666666666666667
3번째 교차검증
학습데이터 건수: 120, 검증데이터 건수: 30
정확도: 0.9333333333333333
4번째 교차검증
학습데이터 건수: 120, 검증데이터 건수: 30
정확도: 0.9333333333333333
5번째 교차검증
학습데이터 건수: 120, 검증데이터 건수: 30
정확도: 1.0
0.9400000000000001


## 교차검증 간단하게 하는법 : cross_val_score
##### stratified KFold 방식을 차용 

In [ ]:
# esimator를 상속받아 만들어짐. 
# 만든 모델을 넣고 X는 독립변수, y는 ㅇㅇ변수
# scoring 정확도
# cv k값?을? 몇개로 나눌건지?
# n_jobs = 1 cpu코어를 1개 쓸건지 2개쓸건지..
# verbos = 0 안찍어줄거면 0.. 1이나2는 관련 로그들이.... ... ..???????

In [301]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn.datasets import load_iris
import numpy as np
import pandas as pd

In [302]:
iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state = 156)

In [303]:
scores = cross_val_score(dt_clf, 
                iris_data.data, # 2딕셔너리형태
                iris_data.target, # 3타겟이라는 컬럼
                scoring='accuracy', cv = 3)   

In [304]:
print("교차검증별 정확도", scores)
print("평균 교차검증 정확도", np.mean(scores))

교차검증별 정확도 [0.98 0.94 0.98]
평균 교차검증 정확도 0.9666666666666667


# GridSearchCV
##### 교차검증과 최적 하이퍼 파라미터 튜닝을 한번에...?

In [397]:
from sklearn.model_selection import GridSearchCV,train_test_split

In [398]:
grid_param = {'max_depth':[1,2,3], 'min_samples_split': [2,3]}

In [410]:
iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size = 0.2, random_state = 121)
dtree = DecisionTreeClassifier()
grid_dtree = GridSearchCV(dtree, param_grid= grid_param, cv = 3, refit = True)
grid_dtree.fit(X_train,y_train) # 지도학습이니 정답을 넣어줌.. y가 정답임

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [1, 2, 3], 'min_samples_split': [2, 3]})

In [411]:
grid_dtree.cv_results_

{'mean_fit_time': array([0.00067663, 0.00068831, 0.00101002, 0.00068839, 0.00134786,
        0.00109982]),
 'std_fit_time': array([4.78698119e-04, 4.94140705e-04, 1.74901691e-05, 4.87643045e-04,
        3.50553820e-04, 8.37289481e-05]),
 'mean_score_time': array([0.00050831, 0.0003322 , 0.00033283, 0.00066384, 0.00049535,
        0.00067695]),
 'std_score_time': array([4.00282618e-04, 4.69796871e-04, 4.70696004e-04, 4.69404722e-04,
        1.26658896e-06, 4.78739137e-04]),
 'param_max_depth': masked_array(data=[1, 1, 2, 2, 3, 3],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_min_samples_split': masked_array(data=[2, 3, 2, 3, 2, 3],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'max_depth': 1, 'min_samples_split': 2},
  {'max_depth': 1, 'min_samples_split': 3},
  {'max_depth': 2, 'min_samples_split': 2},
  {'max_depth': 2, 'min_sa

In [412]:
scores_df = pd.DataFrame(grid_dtree.cv_results_)

In [413]:
scores_df.columns

Index(['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time',
       'param_max_depth', 'param_min_samples_split', 'params',
       'split0_test_score', 'split1_test_score', 'split2_test_score',
       'mean_test_score', 'std_test_score', 'rank_test_score'],
      dtype='object')

In [414]:
scores_df[['params', 'mean_test_score', 'rank_test_score', 'split0_test_score', 'split1_test_score', 'split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

In [415]:
grid_dtree.best_score_

0.975

In [416]:
grid_dtree.best_index_

4

In [417]:
pred = grid_dtree.best_estimator_.predict(X_test)

In [418]:
from sklearn.metrics import accuracy_score

In [419]:
print('best estimator 정확도', accuracy_score(y_test, pred))

best estimator 정확도 0.9666666666666667


In [420]:
from sklearn.preprocessing import LabelEncoder

In [421]:
items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

In [422]:
encoder = LabelEncoder()
encoder.fit(items)
encoder.transform(items)
labels = encoder.transform(items)

In [425]:
labels # 가나다순

array([0, 1, 4, 5, 3, 3, 2, 2])

In [426]:
encoder.classes_

array(['TV', '냉장고', '믹서', '선풍기', '전자레인지', '컴퓨터'], dtype='<U5')

In [427]:
encoder.inverse_transform(labels)

array(['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서'], dtype='<U5')

In [428]:
from sklearn.preprocessing import OneHotEncoder

In [429]:
items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

In [435]:
encodern= LabelEncoder()
labels = encoder.fit_transform(items)
labels

array([0, 1, 4, 5, 3, 3, 2, 2], dtype=int64)

In [438]:
labels.shape

(8,)

In [444]:
labels = labels.reshape(-1,1)
labels.shape

(8, 1)

In [452]:
oh_encoder = OneHotEncoder()
oh_labels = oh_encoder.fit_transform(labels)

In [453]:
oh_encoder.categories_

[array([0, 1, 2, 3, 4, 5], dtype=int64)]

In [454]:
oh_encoder.sparse

True

In [455]:
oh_encoder

OneHotEncoder()

In [456]:
oh_labels.toarray()

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [458]:
df = pd.DataFrame({'item' : ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']})

In [459]:
df

item
0     TV
1    냉장고
2  전자레인지
3    컴퓨터
4    선풍기
5    선풍기
6     믹서
7     믹서

In [461]:
pd.get_dummies(df).values

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0]], dtype=uint8)